version: "3.8"
services:

  mysql-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - wallet-db:/data/db

  wallet-backend:
    depends_on:
      - mysql-db
    image: wallet-backend:dev
    build: ./wallet_backend
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_PORT: 3306
      MYSQL_PASS: $MYSQL_PASSWORD
    ports:
      - $BACKEND_PORT:3000

  wallet-UI:
    depends_on: 
      - wallet-backend
    image: wallet-ui:dev
    build: ./wallet-UI
    environment:
      BACKEND_HOST: wallet-backend
      BACKEND_PORT: $BACKEND_PORT
    ports:
      - $FRONTEND_PORT:80

volumes:
  wallet-db: null
